18.x php update helper
turnkeylinux/common pull request #291
Opened 2024-01-24 01:40 UTC by JedMeister

Minor tweaks to @marcos-mendez's contribution (in #290) - just changes as suggested by shellcheck & a visual adjustment. Plus also adding acknowledgement (that will show up in all relevant changelogs).

Thanks again @marcos-mendez for this awesome contribution. A number of users have been screaming out for this - so you'll make their day. I will get this into the next batch of v18.0 appliances and all future appliances will include it. As PHP v8.3 has only been out a few months, my guess is we won't need to tweak it for v8.4 for some time (I forget their release schedule).

Also are you happy with that acknowledgement line @marcos-mendez? I.e.:
```
[Marcos Méndez @ POPSOLUTIONS <https://github.com/marcos-mendez>]
```

Or would you prefer me include an email address? Any other adjustments?

2024-01-24 02:13 UTC, marcos-mendez commented
LGTM 😎

On Tue, Jan 23, 2024, 22:41 Jeremy Davis ***@***.***> wrote:

> Minor tweaks to @marcos-mendez <https://github.com/marcos-mendez>'s
> contribution (in #290 <https://github.com/turnkeylinux/common/pull/290>)
> - just changes as suggested by shellcheck & a visual adjustment. Plus also
> adding acknowledgement (that will show up in all relevant changelogs).
>
> Thanks again @marcos-mendez <https://github.com/marcos-mendez> for this
> awesome contribution. A number of users have been screaming out for this -
> so you'll make their day. I will get this into the next batch of v18.0
> appliances and all future appliances will include it. As PHP v8.3 has only
> been out a few months, my guess is we won't need to tweak it for v8.4 for
> some time (I forget their release schedule).
>
> Also are you happy with that acknowledgement line @marcos-mendez
> <https://github.com/marcos-mendez>? I.e.:
>
> [Marcos Méndez @ POPSOLUTIONS <https://github.com/marcos-mendez>]
>
> Or would you prefer me include an email address? Any other adjustments?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/turnkeylinux/common/pull/291
> Commit Summary
>
>    - 51b42c0
>    <https://github.com/turnkeylinux/common/pull/291/commits/51b42c0ad109716afb7ea7e23d3daa43fce58a36>
>    insert tkl-upgrade-php.sh
>    - 9b8b726
>    <https://github.com/turnkeylinux/common/pull/291/commits/9b8b726ff4e0a63cad5aa41bbeab9c7441194702>
>    Apply shellcheck & visual tweaks
>    - 570026b
>    <https://github.com/turnkeylinux/common/pull/291/commits/570026b2e6bb4d218822caa034acccc58daf174b>
>    Give Marcos his credit where credit is due :)
>    - 1de5088
>    <https://github.com/turnkeylinux/common/pull/291/commits/1de5088190dad07a29070e21c0fa65b8e16c0fa7>
>    Actually remove file ext - as it's in the PATH
>
> File Changes
>
> (2 files <https://github.com/turnkeylinux/common/pull/291/files>)
>
>    - *M* changes/php.changelog
>    <https://github.com/turnkeylinux/common/pull/291/files#diff-45f3d371f3d9c6c64ac2e41e03108ddcc034dd2f7fd5de2a398425e6f2cea424>
>    (4)
>    - *A* overlays/php/usr/local/bin/tkl-upgrade-php
>    <https://github.com/turnkeylinux/common/pull/291/files#diff-3382b4ddb39605f1fd968ee01c4b5549294beb849a2dd8334864a7a5c8385e15>
>    (85)
>
> Patch Links:
>
>    - https://github.com/turnkeylinux/common/pull/291.patch
>    - https://github.com/turnkeylinux/common/pull/291.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/turnkeylinux/common/pull/291>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJEVVICTB25WYYGBTYSD5HDYQBRDLAVCNFSM6AAAAABCH6PUP6VHI2DSMVQWIX3LMV43ASLTON2WKOZSGA4TOMRWG42DSMY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-24 21:24 UTC, OnGle requested changes
Tiny little change. Otherwise lgtm, thanks for the awesome contribution! :smile:  :partying_face:

2024-01-24 21:24 UTC, OnGle commented on overlays/php/usr/local/bin/tkl-upgrade-php
> +    read -p -r "Enter choice [1-5]: " php_choice
I think this should be `[1-6]`

2024-01-24 22:01 UTC, JedMeister commented on overlays/php/usr/local/bin/tkl-upgrade-php
> +    read -p -r "Enter choice [1-5]: " php_choice
Good catch man!

2024-01-25 00:22 UTC, marcos-mendez commented
My local version is 1 to 6 altought i didnt tested it but it LGTM

On Wed, Jan 24, 2024, 19:01 Jeremy Davis ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In overlays/php/usr/local/bin/tkl-upgrade-php
> <https://github.com/turnkeylinux/common/pull/291#discussion_r1465592457>:
>
> > @@ -0,0 +1,85 @@
> +#!/bin/bash
> +
> +# Function to display PHP version choices and get user input
> +choose_php_version() {
> +    echo "Select the PHP version to install:"
> +    echo "1) PHP 7.3"
> +    echo "2) PHP 7.4"
> +    echo "3) PHP 8.0"
> +    echo "4) PHP 8.1"
> +    echo "5) PHP 8.2"
> +    echo "6) PHP 8.3"
> +    read -p -r "Enter choice [1-5]: " php_choice
>
> Good catch man!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/turnkeylinux/common/pull/291#discussion_r1465592457>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJEVVIB65JSUXIYYNEOXVU3YQGACRAVCNFSM6AAAAABCH6PUP6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBSGQ3DMNBXGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-25 00:50 UTC, JedMeister commented
I'll sort that minor mistake/typo and then merge. Thanks @OnGle & thanks again @marcos-mendez :grin:

2024-01-25 00:52 UTC, merged